package com.example.user.dto;

/**
 * Data Transfer Object for User entity.
 * Used for API requests and responses.
 *
 * This DTO prevents exposing internal entity structure
 * and allows flexible API evolution.
 *
 * Fields:
 * - id: unique identifier (generated by database)
 * - name: user's full name
 * - email: unique email address
 * - age: user's age
 */

public class UserDTO {

    /**
     * Unique user identifier (primary key).
     * Generated automatically by database.
     */
    private Long id;

    /**
     * User's full name.
     * Must not be null or empty.
     */
    private String name;

    /**
     * User's email address.
     * Must be unique across all users.
     * Must not be null or empty.
     */
    private String email;

    /**
     * User's age.
     * Must be a positive integer.
     */
    private Integer age;


        public UserDTO() {
        }

        public UserDTO(Long id, String name, String email, Integer age) {
            this.id = id;
            this.name = name;
            this.email = email;
            this.age = age;
        }

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public Integer getAge() {
            return age;
        }

        public void setAge(Integer age) {
            this.age = age;
        }

}
