package com.example.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for User entity.
 * Used for API requests and responses.
 *
 * This DTO prevents exposing internal entity structure
 * and allows flexible API evolution.
 *
 * Lombok generates:
 * - Getters and setters
 * - equals() and hashCode()
 * - toString()
 * - Constructors
 *
 * Fields:
 * - id: unique identifier (generated by database)
 * - name: user's full name
 * - email: unique email address
 * - age: user's age
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserDTO {

    /**
     * Unique user identifier (primary key).
     * Generated automatically by database.
     */
    private Long id;

    /**
     * User's full name.
     * Must not be null or empty.
     */
    private String name;

    /**
     * User's email address.
     * Must be unique across all users.
     * Must not be null or empty.
     */
    private String email;

    /**
     * User's age.
     * Must be a positive integer.
     */
    private Integer age;
}
